// PF2E — client entry point (LoomVTT native ruleset)
// Generated by _tools/scaffold-ruleset.mjs — mechanics and sheets land in handoffs 02/03.
import { SystemRegistry, defineSystem, statusEffects, sheets } from '/_loom/sdk/index.js';
import { tickTurnEndConditions, resolveTurnActions } from './scripts/conditions.mjs';
import { registerTrackerHooks } from './scripts/tracker-hooks.mjs';
import { registerSettings } from './scripts/settings.mjs';
import { getDefaultData } from './scripts/schema.mjs';
import { prepareActorRow } from './scripts/prepare-data.mjs';
import { getSheetSchema, getItemSheetSchema } from './scripts/sheet-schemas.mjs';
import { SYSTEM_ID, CONDITIONS } from './scripts/config.mjs';
import { Pf2eApi } from './scripts/api.mjs';
import { Pf2eCharacterSheet } from './scripts/character-sheet.mjs';
import { Pf2eNpcSheet } from './scripts/npc-sheet.mjs';
import { Pf2ePartySheet } from './scripts/party-sheet.mjs';
import { Pf2eHazardSheet } from './scripts/hazard-sheet.mjs';
import { Pf2eFamiliarSheet } from './scripts/familiar-sheet.mjs';
import { Pf2eVehicleSheet } from './scripts/vehicle-sheet.mjs';
import { Pf2eItemSheet } from './scripts/item-sheet.mjs';
import { Pf2eCompendiumBrowser } from './scripts/compendium-browser.mjs';
import { registerChatWrapper, sendChatCard, renderPf2eRollCard } from './scripts/chat-card.mjs';
import { initI18n, localize } from './scripts/i18n.mjs';

function prepareData(row) {
  return prepareActorRow(row);
}

initI18n();
registerSettings();

SystemRegistry.register(defineSystem({
  id: SYSTEM_ID,
  title: 'PF2E',
  version: '0.1.0',
  actorTypes: ['character', 'npc', 'group', 'hazard', 'familiar', 'vehicle'],
  itemTypes: ['ancestry', 'heritage', 'background', 'class', 'feat', 'action', 'weapon', 'armor', 'shield', 'equipment', 'consumable', 'spell'],
  getDefaultData,
  getSheetSchema,
  getItemSheetSchema,
  prepareData,
}));

for (const cond of CONDITIONS) {
  if (!statusEffects.get?.(cond.id)) statusEffects.register(cond);
}

sheets.catalog('actor', 'character', Pf2eCharacterSheet);
sheets.catalog('actor', 'npc', Pf2eNpcSheet);
sheets.catalog('actor', 'group', Pf2ePartySheet);
sheets.catalog('actor', 'hazard', Pf2eHazardSheet);
sheets.catalog('actor', 'familiar', Pf2eFamiliarSheet);
sheets.catalog('actor', 'vehicle', Pf2eVehicleSheet);
sheets.catalog('item', '*', Pf2eItemSheet);

registerChatWrapper();
if (typeof window !== 'undefined') {
  if (window.Loom?.LoomHooks?.on) {
    window.Loom.LoomHooks.on('ready', () => registerChatWrapper());

// End of a combatant's turn: its turn-end conditions tick once (e.g. frightened loses 1).
// Only the GM writes. The combatant whose turn just ended is the one before the new current index.
// A linked cast keeps its conditions on the actor; an unlinked cast keeps them on the cast.
registerTrackerHooks();
window.Loom.LoomHooks.on('combatTurn', (combat) => {
  void tickEndedTurnConditions(combat);
  void announceTurnActions(combat);
});

// Combat start: each combatant rolls initiative the pf2e way (d20 plus the actor's own initiative bonus,
// which is perception by default and includes the extra bonus). The core sends these totals to the server.
window.Loom.LoomHooks.on('combatInitiative', (ctx) => {
  for (const castId of ctx.castIds || []) {
    ctx.pending.push(rollPf2eInitiativeFor(castId, ctx));
  }
});

// Posts a ready card straight to chat through the same paths sendChatCard uses first, so no roll is dispatched
// (a dispatched roll with a placeholder formula would leave a total-0 entry in the roll log).
// Returns false when neither path is available, so the caller can fall back.
async function postCardDirect(actor, cardHtml) {
  const speaker = { actor: actor?.id || null, actorId: actor?.id || null, actorName: actor?.name || '', alias: actor?.name || '' };
  const payload = { content: cardHtml, speaker, flags: { pf2e: { cardHtml } } };
  const chatCls = window.Loom?.ChatMessage || window.ChatMessage || window.Loom?.config?.ChatMessage?.documentClass;
  if (chatCls && typeof chatCls.create === 'function') {
    try {
      const res = await chatCls.create(payload);
      if (res) return true;
    } catch (err) {
      console.warn('[pf2e] ChatMessage.create failed for initiative card:', err);
    }
  }
  if (window.Loom?.socket?.emit) {
    const worldId = window.Loom?.world?.id || actor?.worldId || '';
    const userId = window.Loom?.user?.id || '';
    window.Loom.socket.emit('chat.message', { worldId, userId, ...payload });
    return true;
  }
  return false;
}

async function rollPf2eInitiativeFor(castId, ctx) {
  try {
    const cast = await window.Loom.api.get(`/cast/${encodeURIComponent(castId)}`);
    if (!cast?.id) return;
    const holder = cast.isLinked && cast.actorId
      ? await window.Loom.api.get(`/actors/${encodeURIComponent(cast.actorId)}`)
      : cast;
    const bonus = Number(holder?.systemData?.derived?.initiative) || 0;
    // Cryptographic randomness, rolled here so the tracker and the chat card show the same total.
    const d20 = 1 + (crypto.getRandomValues(new Uint32Array(1))[0] % 20);
    const total = d20 + bonus;
    ctx.initiatives[castId] = total;
    const label = localize('pf2e.combat.initiativeTitle', 'Initiative');
    // Same shape as the skill rolls: a pf2e roll with its natural d20, rendered by renderPf2eRollCard.
    // The total is the one already stored in ctx.initiatives, so the card and the tracker agree.
    const roll = {
      formula: bonus ? `1d20 + ${bonus}` : '1d20',
      total,
      mode: 'public',
      terms: [
        { kind: 'dice', count: 1, faces: 20, rolls: [d20] },
        ...(bonus ? [{ kind: 'modifier', value: bonus }] : []),
      ],
      meta: { label, system: 'pf2e', rollType: 'initiative', rollMode: 'public', dc: null },
    };
    const cardHtml = renderPf2eRollCard(roll);
    const posted = await postCardDirect(holder, cardHtml);
    if (!posted) {
      await sendChatCard(holder, {
        name: holder?.name || label, glyph: '⚡', type: label,
        desc: `<strong>${total}</strong> · d20 ${d20} + ${bonus}`,
      });
    }
  } catch (error) {
    console.error(`[pf2e] Could not roll initiative for Cast ${castId}:`, error);
  }
}

// Start of a combatant's turn: post its action budget (resolveTurnActions) to chat. GM only, so it posts once.
async function announceTurnActions(combat) {
  if (!window.Loom?.user?.isGM || !Array.isArray(combat?.combatants) || !combat.combatants.length) return;
  const current = Number(combat.currentTurn);
  if (!Number.isInteger(current)) return;
  const castId = String(combat.combatants[current]?.id || '');
  if (!castId) return;
  try {
    const cast = await window.Loom.api.get(`/cast/${encodeURIComponent(castId)}`);
    if (!cast?.id) return;
    const holder = cast.isLinked && cast.actorId
      ? await window.Loom.api.get(`/actors/${encodeURIComponent(cast.actorId)}`)
      : cast;
    const budget = resolveTurnActions(holder?.systemData?.conditions || {}, 3);
    const parts = [`${budget.actions} ${localize(budget.actions === 1 ? 'pf2e.combat.actionOne' : 'pf2e.combat.actionMany')}`];
    if (budget.reaction) parts.push(localize('pf2e.combat.reaction'));
    if (budget.quickened) parts.push(localize('pf2e.combat.quickened'));
    if (budget.stunnedRemainder) parts.push(`${localize('pf2e.combat.stunned')} ${budget.stunnedRemainder}`);
    await sendChatCard(holder, { name: holder?.name || localize('pf2e.combat.turnTitle'), glyph: '◆', type: localize('pf2e.combat.turnTitle'), desc: parts.join(' · ') });
  } catch (error) {
    console.error(`[pf2e] Could not announce the turn actions for Cast ${castId}:`, error);
  }
}

async function tickEndedTurnConditions(combat) {
  if (!window.Loom?.user?.isGM || !Array.isArray(combat?.combatants) || !combat.combatants.length) return;
  const current = Number(combat.currentTurn);
  if (!Number.isInteger(current)) return;
  // The first turn of a combat has no previous combatant that has taken a turn yet.
  if (current === 0 && Number(combat.round) <= 1) return;
  const endedIndex = (current - 1 + combat.combatants.length) % combat.combatants.length;
  const castId = String(combat.combatants[endedIndex]?.id || '');
  if (!castId) return;
  // The server replaces systemData as a whole, so a plain read-then-write can drop a concurrent edit.
  // Re-read before writing and retry only if the stored conditions changed in between.
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const cast = await window.Loom.api.get(`/cast/${encodeURIComponent(castId)}`);
      if (!cast?.id) return;
      const linked = cast.isLinked && cast.actorId;
      const holderPath = linked ? `/actors/${encodeURIComponent(cast.actorId)}` : `/cast/${encodeURIComponent(castId)}`;
      const holder = linked ? await window.Loom.api.get(holderPath) : cast;
      const systemData = holder?.systemData || {};
      const before = systemData.conditions || {};
      const after = tickTurnEndConditions(before);
      if (JSON.stringify(before) === JSON.stringify(after)) return;
      const latest = await window.Loom.api.get(holderPath);
      const latestConditions = latest?.systemData?.conditions || {};
      if (JSON.stringify(latestConditions) !== JSON.stringify(before)) continue;
      await window.Loom.api.put(holderPath, { systemData: { ...(latest.systemData || {}), conditions: after } });
      return;
    } catch (error) {
      console.error(`[pf2e] Could not tick turn-end conditions for Cast ${castId}:`, error);
      return;
    }
  }
}
  }
  if (!window.ChatMessage && window.Loom?.ChatMessage) {
    window.ChatMessage = window.Loom.ChatMessage;
  }
}

Pf2eApi.compendiumBrowser = Pf2eCompendiumBrowser;
Pf2eApi.openCompendiumBrowser = () => Pf2eCompendiumBrowser.open();

window.PF2E = Pf2eApi;

