// PF2E — scripts/conditions.mjs
// Condition definitions, classification metadata, modifier extraction, and turn transitions.
// Compliant with Pathfinder 2e Remaster rules.
import { createModifier } from './modifiers.mjs';

function num(v) {
  const n = Number(v);
  return Number.isFinite(n) ? n : 0;
}

/**
 * Detailed metadata classification for every standard PF2e condition:
 * - 'numerical': directly adjusts rolls, DCs, or statistics through typed modifiers
 * - 'action-restriction': alters action budget or permitted activities (slowed, stunned, quickened, etc.)
 * - 'contextual-state': requires situational adjudication, target relation, or flat checks (concealed, hidden, etc.)
 * - 'temporal-transition': progresses or reduces on specific turn/round boundaries (frightened, dying, wounded, etc.)
 */
export const CONDITION_METADATA = {
  blinded: { category: 'contextual-state', flatCheckDC: 11, valued: false },
  clumsy: { category: 'numerical', valued: true },
  concealed: { category: 'contextual-state', flatCheckDC: 5, valued: false },
  confused: { category: 'action-restriction', valued: false },
  controlled: { category: 'action-restriction', valued: false },
  dazzled: { category: 'contextual-state', flatCheckDC: 5, valued: false },
  deafened: { category: 'numerical', flatCheckDC: 5, valued: false },
  doomed: { category: 'temporal-transition', valued: true },
  drained: { category: 'numerical', valued: true },
  dying: { category: 'temporal-transition', valued: true },
  enfeebled: { category: 'numerical', valued: true },
  fascinated: { category: 'action-restriction', valued: false },
  fatigued: { category: 'numerical', valued: false },
  fleeing: { category: 'action-restriction', valued: false },
  frightened: { category: 'temporal-transition', valued: true },
  grabbed: { category: 'contextual-state', flatCheckDC: 5, valued: false },
  hidden: { category: 'contextual-state', flatCheckDC: 11, valued: false },
  immobilized: { category: 'action-restriction', valued: false },
  invisible: { category: 'contextual-state', flatCheckDC: 11, valued: false },
  'off-guard': { category: 'numerical', valued: false },
  paralyzed: { category: 'action-restriction', valued: false },
  petrified: { category: 'action-restriction', valued: false },
  prone: { category: 'numerical', valued: false },
  quickened: { category: 'action-restriction', valued: false },
  restrained: { category: 'action-restriction', flatCheckDC: 5, valued: false },
  sickened: { category: 'numerical', valued: true },
  slowed: { category: 'action-restriction', valued: true },
  stunned: { category: 'action-restriction', valued: true },
  stupefied: { category: 'numerical', valued: true },
  unconscious: { category: 'temporal-transition', valued: false },
  undetected: { category: 'contextual-state', valued: false },
  wounded: { category: 'temporal-transition', valued: true },
};

/**
 * Extracts all active modifiers generated by conditions on an actor.
 * @param {Record<string, any>} conditions Map of condition id -> value or boolean
 * @returns {import('./modifiers.mjs').Modifier[]}
 */
export function getConditionModifiers(conditions = {}) {
  const modifiers = [];

  for (const [key, val] of Object.entries(conditions || {})) {
    if (!val) continue;
    const value = typeof val === 'number' ? num(val) : (typeof val === 'object' && val.value ? num(val.value) : 1);
    if (value <= 0) continue;

    const conditionKey = key.toLowerCase();

    switch (conditionKey) {
      case 'frightened':
        modifiers.push(createModifier({
          id: `condition-frightened-${value}`,
          sourceId: 'condition-frightened',
          slug: 'frightened',
          label: `Frightened ${value}`,
          labelKey: 'pf2e.conditions.frightened',
          type: 'status',
          value: -value,
          selectors: ['all-checks', 'ac', 'saves', 'perception', 'spell-dc', 'class-dc', 'attack'],
        }));
        break;

      case 'sickened':
        modifiers.push(createModifier({
          id: `condition-sickened-${value}`,
          sourceId: 'condition-sickened',
          slug: 'sickened',
          label: `Sickened ${value}`,
          labelKey: 'pf2e.conditions.sickened',
          type: 'status',
          value: -value,
          selectors: ['all-checks', 'ac', 'saves', 'perception', 'spell-dc', 'class-dc', 'attack'],
        }));
        break;

      case 'clumsy':
        modifiers.push(createModifier({
          id: `condition-clumsy-${value}`,
          sourceId: 'condition-clumsy',
          slug: 'clumsy',
          label: `Clumsy ${value}`,
          labelKey: 'pf2e.conditions.clumsy',
          type: 'status',
          value: -value,
          selectors: ['dex-checks', 'ac', 'reflex', 'stealth', 'acrobatics', 'thievery', 'ranged-attack'],
        }));
        break;

      case 'enfeebled':
        modifiers.push(createModifier({
          id: `condition-enfeebled-${value}`,
          sourceId: 'condition-enfeebled',
          slug: 'enfeebled',
          label: `Enfeebled ${value}`,
          labelKey: 'pf2e.conditions.enfeebled',
          type: 'status',
          value: -value,
          selectors: ['str-checks', 'athletics', 'melee-damage'],
        }));
        break;

      case 'stupefied':
        modifiers.push(createModifier({
          id: `condition-stupefied-${value}`,
          sourceId: 'condition-stupefied',
          slug: 'stupefied',
          label: `Stupefied ${value}`,
          labelKey: 'pf2e.conditions.stupefied',
          type: 'status',
          value: -value,
          selectors: [
            'mental-checks',
            'int-checks',
            'wis-checks',
            'cha-checks',
            'will',
            'spell-attack',
            'spell-dc',
            'arcana',
            'crafting',
            'deception',
            'diplomacy',
            'intimidation',
            'medicine',
            'nature',
            'occultism',
            'performance',
            'religion',
            'society',
            'survival',
          ],
        }));
        break;

      case 'drained':
        modifiers.push(createModifier({
          id: `condition-drained-${value}`,
          sourceId: 'condition-drained',
          slug: 'drained',
          label: `Drained ${value}`,
          labelKey: 'pf2e.conditions.drained',
          type: 'status',
          value: -value,
          selectors: ['con-checks', 'fortitude'],
        }));
        break;

      case 'fatigued':
        modifiers.push(createModifier({
          id: 'condition-fatigued-ac',
          sourceId: 'condition-fatigued',
          slug: 'fatigued-ac',
          label: 'Fatigued',
          labelKey: 'pf2e.conditions.fatigued',
          type: 'status',
          value: -1,
          selectors: ['ac'],
        }));
        modifiers.push(createModifier({
          id: 'condition-fatigued-saves',
          sourceId: 'condition-fatigued',
          slug: 'fatigued-saves',
          label: 'Fatigued',
          labelKey: 'pf2e.conditions.fatigued',
          type: 'status',
          value: -1,
          selectors: ['saves', 'fortitude', 'reflex', 'will'],
        }));
        break;

      case 'off-guard':
        modifiers.push(createModifier({
          id: 'condition-off-guard',
          sourceId: 'condition-off-guard',
          slug: 'off-guard',
          label: 'Off-Guard',
          labelKey: 'pf2e.conditions.off-guard',
          type: 'circumstance',
          value: -2,
          selectors: ['ac'],
        }));
        break;

      case 'prone':
        modifiers.push(createModifier({
          id: 'condition-prone-attack',
          sourceId: 'condition-prone-attack',
          slug: 'prone-attack',
          label: 'Prone (attack penalty)',
          labelKey: 'pf2e.conditions.prone',
          type: 'circumstance',
          value: -2,
          selectors: ['attack'],
        }));
        modifiers.push(createModifier({
          id: 'condition-prone-ac',
          sourceId: 'condition-prone-ac',
          slug: 'off-guard',
          label: 'Off-Guard (Prone)',
          labelKey: 'pf2e.conditions.off-guard',
          type: 'circumstance',
          value: -2,
          selectors: ['ac'],
        }));
        break;

      case 'blinded':
        modifiers.push(createModifier({
          id: 'condition-blinded-ac',
          sourceId: 'condition-blinded-ac',
          slug: 'off-guard',
          label: 'Off-Guard (Blinded)',
          type: 'circumstance',
          value: -2,
          selectors: ['ac'],
        }));
        modifiers.push(createModifier({
          id: 'condition-blinded-perception',
          sourceId: 'condition-blinded-perception',
          slug: 'blinded',
          label: 'Blinded',
          type: 'status',
          value: -4,
          selectors: ['perception'],
        }));
        break;

      case 'deafened':
        modifiers.push(createModifier({
          id: 'condition-deafened-perception',
          sourceId: 'condition-deafened-perception',
          slug: 'deafened',
          label: 'Deafened (Perception)',
          type: 'status',
          value: -2,
          selectors: ['perception'],
        }));
        break;

      case 'unconscious':
        modifiers.push(createModifier({
          id: 'condition-unconscious-ac',
          sourceId: 'condition-unconscious',
          slug: 'unconscious-ac',
          label: 'Unconscious AC penalty',
          type: 'status',
          value: -4,
          selectors: ['ac'],
        }));
        modifiers.push(createModifier({
          id: 'condition-unconscious-off-guard',
          sourceId: 'condition-unconscious',
          slug: 'off-guard',
          label: 'Off-Guard (Unconscious)',
          type: 'circumstance',
          value: -2,
          selectors: ['ac'],
        }));
        modifiers.push(createModifier({
          id: 'condition-unconscious-reflex',
          sourceId: 'condition-unconscious',
          slug: 'unconscious-reflex',
          label: 'Unconscious Reflex penalty',
          type: 'status',
          value: -4,
          selectors: ['reflex'],
        }));
        modifiers.push(createModifier({
          id: 'condition-unconscious-perception',
          sourceId: 'condition-unconscious',
          slug: 'unconscious-perception',
          label: 'Unconscious Perception penalty',
          type: 'status',
          value: -4,
          selectors: ['perception'],
        }));
        break;

      default:
        break;
    }
  }

  return modifiers;
}

/**
 * Returns the Flat Check DC required when targeting or acting under a contextual condition.
 * @param {string} conditionName
 * @param {number} [stupefiedVal=0]
 * @returns {number|null}
 */
export function getFlatCheckDC(conditionName, stupefiedVal = 0) {
  const cond = String(conditionName || '').toLowerCase();
  if (cond === 'concealed' || cond === 'dazzled') return 5;
  if (cond === 'hidden' || cond === 'blinded' || cond === 'invisible') return 11;
  if (cond === 'stupefied') return 5 + Math.max(1, num(stupefiedVal));
  if (cond === 'grabbed' || cond === 'restrained' || cond === 'deafened') return 5;
  return null;
}

/**
 * Ticks conditions at the end of a combatant's turn.
 * Frightened decreases by 1 on turn end.
 * Returns a new conditions object with expired conditions removed.
 *
 * @param {Record<string, any>} conditions
 * @returns {Record<string, any>}
 */
export function tickTurnEndConditions(conditions = {}) {
  const next = JSON.parse(JSON.stringify(conditions || {}));
  if (next.frightened) {
    const current = num(next.frightened);
    if (current > 1) {
      next.frightened = current - 1;
    } else {
      delete next.frightened;
    }
  }
  return next;
}

/**
 * Calculates turn action budget considering slowed, stunned, quickened, unconscious, etc.
 * @param {Record<string, any>} conditions
 * @param {number} [baseActions=3]
 * @returns {{ actions: number, quickened: boolean, reaction: boolean, stunnedRemainder: number }}
 */
export function resolveTurnActions(conditions = {}, baseActions = 3) {
  if (conditions.unconscious || conditions.paralyzed || conditions.petrified) {
    return { actions: 0, quickened: false, reaction: false, stunnedRemainder: 0 };
  }

  let actions = baseActions;
  let reaction = true;
  let quickened = !!conditions.quickened;

  // Stunned: reduces actions by value; if stunned exceeds actions, stunned remains with difference
  let stunnedRemainder = 0;
  if (conditions.stunned) {
    const stunVal = num(conditions.stunned);
    if (stunVal >= actions) {
      stunnedRemainder = stunVal - actions;
      actions = 0;
      reaction = false;
    } else {
      actions -= stunVal;
    }
  }

  // Slowed: reduces actions by value at start of turn
  if (actions > 0 && conditions.slowed) {
    const slowVal = num(conditions.slowed);
    actions = Math.max(0, actions - slowVal);
  }

  // Quickened: adds 1 action (only if actor can take actions)
  if (actions > 0 && quickened) {
    actions += 1;
  }

  return {
    actions,
    quickened,
    reaction,
    stunnedRemainder,
  };
}
